dependencies:
  - name: mysql
    version: "0.19.x"
    repository: "https://kubernetes-charts.storage.googleapis.com"
    condition: mysql.enabled
  - name: rabbitmq
    version: "2.2.x"
    repository: "https://kubernetes-charts.storage.googleapis.com"
    condition: rabbitmq.enabled
