dependencies:
  - name: mariadb
    version: "6.12.2"
    repository: "https://kubernetes-charts.storage.googleapis.com"
    condition: mariadb.enabled
  - name: rabbitmq
    version: "6.x.x"
    repository: "https://kubernetes-charts.storage.googleapis.com"
    condition: rabbitmq.enabled
