apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstackIronicStandalone.api.fullname" . }}
  {{- with .Values.api.service_annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    app: {{ include "openstackIronicStandalone.name" . }}
    chart: {{ include "openstackIronicStandalone.chart" . }}
    component: {{ .Values.api.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ include "openstackIronicStandalone.name" . }}
    component: {{ .Values.api.name }}
    release: {{ .Release.Name }}
  type: {{ .Values.api.service_type }}
  ports:
    - name: ironic-api
      port: {{ .Values.api.portExternal }}
      targetPort: {{ .Values.api.portInternal }}
  {{- if .Values.api.loadBalancerIP }}
  loadBalancerIP: {{ .Values.api.loadBalancerIP }}
  {{- end }}
  {{- with .Values.api.externalIPs }}
  externalIPs:
{{ toYaml . | indent 4 }}
  {{- end }}

