apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openstackIronicStandalone.name" . }}-db-scripts
  labels:
    app: {{ include "openstackIronicStandalone.name" . }}
    chart: {{ include "openstackIronicStandalone.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  wait-for-mariadb.sh: |
    <%!
        import os
    %>
    #!/bin/bash
    
    DB="{{ .Release.Name }}-mariadb"
    USER="{{ default "root" .Values.mariadb.db.user }}"
    PASS="${os.environ.get('MARIADB_PASSWORD','')}"
    
    while ! mariadb -u "${USER}" --password="${PASS}" -h "${DB}" -e 'show databases;' >/dev/null 2>&1
    do
      sleep 1
      echo -n "."
    done
