{{- if .Values.keystone.enabled -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Release.Name }}-keystone
  labels:
    app.kubernetes.io/name: {{ include "openstackIronicStandalone.name" $ }}
    helm.sh/chart: {{ include "openstackIronicStandalone.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  admin_password: {{ $.Values.keystone.admin_password | b64enc }}
  ironic_password: {{ $.Values.keystone.ironic_password | b64enc }}
{{- end -}}
