{{- if not .Values.mariadb.enabled -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Release.Name }}-mariadb
  labels:
    app.kubernetes.io/name: {{ include "openstackIronicStandalone.name" $ }}
    helm.sh/chart: {{ include "openstackIronicStandalone.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  mariadb-password: {{ $.Values.mariadb.db.password }}
  mariadb-root-password: {{ $.Values.mariadb.rootUser.password }}
{{- end -}}
