{{- if not .Values.mysql.enabled -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Release.Name }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "openstackIronicStandalone.name" $ }}
    helm.sh/chart: {{ include "openstackIronicStandalone.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  mysql-password: {{ $.Values.mysql.mysqlPassword }}
  mysql-root-password: {{ $.Values.mysql.mysqlRootPassword }}
{{- end -}}
