apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "openstackIronicStandalone.tftp.fullname" . }}
  labels:
    app: {{ include "openstackIronicStandalone.name" . }}
    chart: {{ include "openstackIronicStandalone.chart" . }}
    component: {{ .Values.tftp.name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "openstackIronicStandalone.name" . }}
      component: {{ .Values.tftp.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "openstackIronicStandalone.tftp.fullname" . }}
      labels:
        app: {{ include "openstackIronicStandalone.name" . }}
        component: {{ .Values.tftp.name }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      hostNetwork: true
    {{- with .Values.tftp.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
        - name: tftpd
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          tty: true
          command: 
            - /bin/sh
          args:
            - -c
            - rsyslogd -n & /usr/sbin/in.tftpd --ipv4 -v --foreground --map-file /etc/tftp-map-file /tftpboot
          volumeMounts:
            - mountPath: /tftpboot
              name: ironic
              subPath: tftpboot
            - mountPath: /etc/tftp-map-file
              name: ironic-etc
              subPath: tftp-map-file
              readOnly: true
        {{- with .Values.tftp.resources }}
          resources:
{{ toYaml . | indent 12 }}
        {{- end }}
        - name: httpd
          image:  "{{ .Values.httpboot.image.name }}:{{ .Values.httpboot.image.version }}"
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: ironic-etc
              subPath: httpd.conf
              readOnly: true
            - mountPath: /usr/share/nginx/html
              name: ironic
              {{- if .Values.config.pxe.ipxe_enabled }}
              subPath: httpboot
              {{- else }}
              subPath: tftpboot
              {{- end }}
            - mountPath: /usr/share/nginx/html/boot.ipxe
              name: ironic-etc
              subPath: boot.ipxe
      volumes:
        - name: ironic
          persistentVolumeClaim:
            {{- if .Values.persistentVolumeClaimName }}
            claimName: {{ .Values.persistentVolumeClaimName | quote }}
            {{- else }}
            claimName: {{ ( include "openstackIronicStandalone.tftp.fullname" . ) | quote }}
            {{- end }}
        - name: ironic-etc
          configMap:
            name: {{ include "openstackIronicStandalone.name" . }}-etc
            defaultMode: 0644
